[package]
name = "he-core-lib"
version = "0.0.0"
authors = ["James Whaley <juicy66173@gmail.com>"]
description = "Library module for he-core."
license = "MIT/Apache-2.0"
edition = "2018"

repository = "https://github.com/Juici/he"

[dependencies]
